name: Continuous Delivery Pipe

on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Where to release (staging or prod)?'     
        required: true
        default: 'dev'

jobs:
  dev:
    name: Deploy to Develop
    environment: 
      name: Develop
      url: https://dotnetmona-dev.azurewebsites.net/
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

  staging:
    name: Deploy to Staging
    environment: 
      name: Staging
      url: https://dotnetmona-staging.azurewebsites.net/
    needs: [dev]
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
  prod:
    name: Deploy to Prod
    environment: 
        name: Production
        url: https://dotnetmona.azurewebsites.net/
    needs: [staging]
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2