name: Continuous Delivery Pipe

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Where to release (stage or prod)?'     
        required: true
        default: 'stage'

jobs:
  stage:
    name: Deploy to Stage
    environment: 
      name: Staging
      url: https://dotnetmona-staging.azurewebsites.net/
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.releaseType == 'staging' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
  prod:
    name: Deploy to Prod
    environment: 
        name: Production
        url: https://dotnetmona.azurewebsites.net/
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.releaseType == 'prod' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2