name: Continuous Integration Pipe

on:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'uat'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'uat'

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test
  
  deploy:
    name: Deploy to Develop
    environment: 
      name: Develop
      url: https://dotnetmona-dev.azurewebsites.net/
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
    needs: [build]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4